### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by YaroShkvorets** [pomelo-io/pomelo-grants-contract#14]
![image.png](https://images.zenhubusercontent.com/62b09e1aba912da7d1709966/19514ef8-58ee-4871-9693-9a47041add6d)

![image.png](https://images.zenhubusercontent.com/62b09e1aba912da7d1709966/94bae7bf-8c6d-48f4-ae47-338d2c4aadfa)

Errors are not descriptive.
Should mention the grant name because when donating to multiple projects from cart it's hard to track down the problematic grant

**Comment by chillsauce** [comment]
good one 👍
