### ISSUE TITLE
Add TLOS oracle

### ISSUE THREAD

**Issue by YaroShkvorets** [pomelo-io/pomelo-grants-contract#17]
Need TLOS/USDT price.

**Comment by YaroShkvorets** [comment]
Implemented, deployed to production.

**Comment by UrsaPolarisRecords** [comment]
swap.defi 

id 2136 | { "contract": "ibc.wt.tlos", "symbol": "4,TLOS" } | { "contract": "eosio.token", "symbol": "4,EOS" } | 199942.7749 TLOS

Side note, this is TLOS/EOS price not TLOS/USDT price.
